spring.application.name=demoDietiEstatesBE

spring.datasource.url=jdbc:postgresql://localhost:5432/dietiestates
spring.datasource.username=postgres
spring.datasource.password=LA_TUA_PASSWORD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
