@startuml
skinparam linetype ortho
skinparam packageStyle rectangle
skinparam classAttributeIconSize 0
skinparam class {
  BackgroundColor White
  BorderColor #333
  ArrowColor #555
}

package "repositories" #LightGreen {

  interface UtenteRepo <<JpaRepository<Utente, UUID>>> {
    + findByEmail(email) : Optional<Utente>
    + existsByEmail(email) : boolean
    + findAllByAgenzia(id) : List<Utente>
    + findByIdUtente(findByIdUtente) : Optional<Utente>
  }

  interface AgenteRepo <<JpaRepository<Agente, UUID>>> {
    + findByEmail(email) : Optional<Agente>
    + findByAgenzia_IdAgenzia(idAgenzia) : List<Agente>
  }

  interface ClienteRepo <<JpaRepository<Cliente, UUID>>> {
    + findByEmail(email) : Optional<Cliente>
    + findByIdUtente(idUtente) : Optional<Cliente>
  }

  interface GestoreRepo <<JpaRepository<Gestore, UUID>>> {
    + existsByAgenziaIdAgenzia(idAgenzia) : boolean
  }

  interface SupportoRepo <<JpaRepository<SupportoAmministratore, UUID>>> {
  }

  interface AgenziaRepo <<JpaRepository<Agenzia, Integer>>> {
    + findByNomeAgenziaIgnoreCase(nomeAgenzia) : Optional<Agenzia>
    + existsByPartitaIva(partitaIva) : boolean
  }

  interface ImmobileRepo <<JpaRepository<Immobile, Integer>>> {
    + findByLocationRange(minLat, maxLat, minLon, maxLon) : List<Immobile>
    + searchImmobiliAvanzata(citta, min, max, contratto) : List<Immobile>
    + findByAgenziaAgentiIdUtente(idUtente) :List<Immobile>  
    + findByAgenzia_IdAgenzia(idAgenzia): List<Immobile>
  }

  interface ImmobileImmagineRepo <<JpaRepository<ImmobileImmagine, Integer>>> {
    + findByImmobileIdImmobile(idImmobile) : List<ImmobileImmagine>
    + findByImmobileIdImmobileAndIsCopertinaTrue(idImmobile) : List<ImmobileImmagine>
  }

  interface OffertaRepo <<JpaRepository<Offerta, Integer>>> {
    + findByCliente_IdUtente(idCliente) : List<Offerta>
    + findByImmobile_IdImmobile(idImmobile) : List<Offerta>
    + findByImmobile_Agente_IdUtente(idAgente) : List<Offerta>
    + findByClienteAndOffertaEsternaFalse(cliente) : List<Offerta>
    + findByCliente(cliente) : List<Offerta>
    + findByImmobile_Agente_IdUtenteAndStato(idAgente, stato) : List<Offerta>
    + findByImmobile_Agente_IdUtenteAndStatoIn(idAgente, stati) : List<Offerta>
  }

  interface StoricoRepo <<JpaRepository<StoricoOfferta, Integer>>> {
    + findByOffertaIdOffertaOrderByDataAzioneDesc(idOfferta) : List<StoricoOfferta>
    + findByOfferta(offerta) : List<StoricoOfferta>
    + findByOffertaOrderByIdLogDesc(offerta) : List<StoricoOfferta>
  }
}
@enduml