@startuml DietiEstates2_Services_Controllers

skinparam linetype ortho
skinparam packageStyle rectangle
skinparam classAttributeIconSize 0
skinparam class {
  BackgroundColor White
  BorderColor #333
  ArrowColor #555
}

package "services" #LightPink {

  class AuthService {
    + login(email, password) : Map<String,String>
    + signUp(email, password) : String
    + registraCliente(dto) : void
    + adminCreateUser(email) : String
    + addUserToGroup(email, groupName) : void
    + setUserPasswordPermanent(email, password) : void
    + confirmUser(email) : void
    + updatePassword(token, old, new) : void
    + calculateSecretHash( clientId, clientSecret, userName) : String
    + deleteUser(email) : void
  }

  class UtenteService {
    + findAll() : List<UtenteDTO>
    + findById(id) : UtenteDTO
    + existsByEmail(email) : boolean
    + delete(id) : void
    + save(dto) :  UtenteDTO
    + registraCliente(dto) : UtenteDTO
    + creaStaff(dto) : UtenteDTO
  }

  class AgenziaService {
    + findAll() : List<AgenziaDTO>
    + findById(id) : AgenziaDTO
    + save(dto) : AgenziaDTO
    + delete(id) : void
  }

  class AmministratoreService {
    + creaGestore(dto) : GestoreDTO
    + creaSupporto(dto) : SupportoAmministratoreDTO
  }

  class GestoreService {
    + creaAgente(idGestore, dto) : AgenteDTO
    + getAgentiAgenzia(idGestore) : List<AgenteDTO>
    + getImmobiliAgenzia(idGestore) : List<ImmobileDTO>
    + aggiornaAgente(idAgente, dto) : AgenteDTO 
    + eliminaAgente(idAgente) : void
  }

  class AgenteService {
    + getProfiloAgente(id) : AgenteDTO
    + caricaImmobile(dto, idAgente) : ImmobileDTO
    + checkServiziZona(immobile): void
    + aggiornaImmobile(idImmobile, dto) : ImmobileDTO
    + inserisciOffertaEsterna(dto, idImmobile) : OffertaDTO
    + gestisciOfferta(idOfferta, stato, prezzo, nota, idAgente) : OffertaDTO
    + getOffertePerAgente(idAgente) : List<OffertaDTO>
    + getOfferteAttivePerAgente(idAgente) : List<OffertaDTO>
    + getStoricoOfferta(idOfferta, idAgente) : List<StoricoOffertaDTO>
  }

  class ClienteService {
    + inviaOfferta(dto, idCliente) : OffertaDTO
    + aggiornaStatoOfferta(idOfferta, idCliente, stato) : OffertaDTO
    + getOffertePerCliente(uuidUtente) : List<OffertaDTO>
  }

  class ImmobileService {
    + getAllImmobili(pageable) : Page<ImmobileDTO>
    + getImmobileById(id) : ImmobileDTO
    + searchImmobili(citta, min, max, contratto) : List<ImmobileDTO>
    + saveImmobileFromDTO(dto) : ImmobileDTO
    + updateImmobile(id,dto) : ImmobileDTO
    + deleteImmobile(idAgente) : void
    + getImmobiliByAgenteAgenzia(idAgente) : List<ImmobileDTO>
  }

  class OffertaService {
    + createOfferta(dto) : OffertaDTO
    + aggiornaStato(id, stato, controfferta) : OffertaDTO
    + findAll() : List<OffertaDTO>
    + findByCliente(idCliente) : List<OffertaDTO>
    + getOffertePerImmobile(idImmobile) : List<OffertaDTO>
    + getOffertePerAgente(idAgente) : List<OffertaDTO>
  }

  class ImmagineService {
    + aggiungiImmagine(idImmobile, url, copertina) : ImmobileImmagineDTO
    + eliminaImmagine(idImmagine) : void
  }

  class GeoService {
    + getCoordinates(address) : Map<String,Double>
    + isNear(lat, lon, category) : boolean
  }

  ' Dipendenze tra service
  AmministratoreService --> AuthService
  GestoreService --> AuthService
  AgenteService --> GeoService
  ImmobileService --> GeoService
  UtenteService --> AuthService
}

package "controllers" #Lavender {

  class AuthController {
    POST /api/auth/login
    POST /api/auth/signup-cliente
    POST /api/auth/setup-admin
  }

  class UtenteController {
    GET    /api/utente
    GET    /api/utente/{id}
    POST    /api/utente
    POST   /api/utente/update-password
    DELETE /api/utente/{id}
  }

  class AgenziaController {
    GET    /api/agenzia
    GET    /api/agenzia/{id}
    POST   /api/agenzia
    DELETE /api/agenzia/{id}
    PUT    /api/agenzia/{id}
  }

  class AmministratoreController {
    POST /api/amministratore/registra-gestore
    POST /api/amministratore/registra-supporto
  }

  class GestoreController {
    POST /api/gestore/registra-agente
    GET /api/gestore/miei-agenti
    GET /api/gestore/immobili-agenzia
    DELETE /api/gestore/agente/{id}
    PATCH /api/gestore/agente/{id}


  }

  class AgenteController {
    GET   /api/agente/profilo
    GET   /api/agente/offerte-ricevute
    GET   /api/agente/offerte/attive
    POST  /api/agente/immobili
    PUT   /api/agente/aggiorna-immobile/{id}
    POST  /api/agente/immobili/{idImmobile}/offerta-esterna
    PATCH /api/agente/offerte/{idOfferta}
  }

  class ClienteController {
    POST  /api/cliente/offerte/crea
    PATCH /api/cliente/offerte/{idOfferta}/rispondi
    GET   /api/cliente/mie-offerte
  }

  class ImmobileController {
    GET    /api/immobile
    GET    /api/immobile/cerca
    GET    /api/immobile/{id}
    GET    /api/immobile/mio-organiico/{idAgente}
    POST   /api/immobile
    PUT    /api/immobile/{id}
    DELETE /api/immobile/{id}
  }

  class OffertaController {
    GET   /api/offerta
    GET   /api/offerta/immobile/{id}
    GET   /api/offerta/cliente/{idCliente}
    POST  /api/offerta
    PATCH /api/offerta/{id}/stato
  }

  class ImmagineController {
    POST   /api/immobile/immagine/{idImmagine}
    DELETE /api/immobile/immagine/{idImmagine}
  }

  ' Controller -> Service
  AuthController --> AuthService
  UtenteController --> UtenteService
  UtenteController --> AuthService
  AgenziaController --> AgenziaService
  AmministratoreController --> AmministratoreService
  GestoreController --> GestoreService
  AgenteController --> AgenteService
  ClienteController --> ClienteService
  ImmobileController --> ImmobileService
  OffertaController --> OffertaService
  ImmagineController --> ImmagineService
}

@enduml
