spring.application.name=DietiEstates2

# --- DATASOURCE ---
spring.datasource.url=jdbc:postgresql://localhost:5432/DietiEstates2?ssl=false
spring.datasource.username=postgres
spring.datasource.password=Merdarella1
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Dialect specifico per PostgreSQL
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# --- SCHEMA DI DEFAULT ---
spring.jpa.properties.hibernate.default_schema=dietiestates

aws.cognito.userPoolId=eu-north-1_egBpYxech
aws.cognito.clientId=4q8lvdfc7bopkivv96rm1l8hcv
aws.cognito.clientSecret=1ptm7622qbnlom1a0slr9qp26c66dgofmu3bj3uqfkjk20r868ie
aws.region=eu-north-1

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.eu-north-1.amazonaws.com/eu-north-1_egBpYxech
#logging.level.org.springframework.security=DEBUG
aws.accessKeyId=AKIA3UTIBAWBODEZGLGC
aws.secretAccessKey=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

