spring.application.name=DietiestatesApp

# --- DATASOURCE ---
spring.datasource.url=jdbc:postgresql://localhost:5432/Dietiestates?ssl=false
spring.datasource.username=postgres
spring.datasource.password=Merdarella1
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Dialect specifico per PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# --- SCHEMA DI DEFAULT ---
spring.jpa.properties.hibernate.default_schema=dietiestes
